L79508E:										;char* string_resources[] = {
	dc.l	0xFFCA9170
	dc.l	0xFFCA9190
	dc.l	0xFFCA91F0
	dc.l	0xFFCA92B8
	dc.l	0xFFCA9320
	dc.l	0xFFCA9380
	dc.l	0xFFCA9358
	dc.l	0xFFCA93B8
	dc.l	0xFFCA92E8
	dc.l	0xFFCA93E8
	dc.l	0xFFCA9430
	dc.l	0xFFCA9458
	dc.l	0xFFCA9480
	dc.l	0xFFCA94B8
	dc.l	L7952F6								;0x0E
	dc.l	0xFFCB0AF0
	dc.l	0xFFCB0B40 
	dc.l	0xFFCB0C90
	dc.l	0xFFCB0C40
	dc.l	L79619A								;0x13
	dc.l	0xFFCA94E0
	dc.l	0xFFCA9958
	dc.l	0xFFCB0BA8 
	dc.l	0xFFCB0BD8
	dc.l	0xFFCA9520
	dc.l	0xFFCA9550
	dc.l	0xFFCA9580
	dc.l	L7952B2								;0x1B
	dc.l	0xFFCA95C8
	dc.l	0xFFCA9600
	dc.l	0xFFCA9630
	dc.l	0xFFCA9660
	dc.l	0xFFCA9670
	dc.l	0xFFCA9B00
	dc.l	0xFFCA9698
	dc.l	0xFFCA96E0
	dc.l	0xFFCA9CD0
	dc.l	0xFFCA9E30
	dc.l	0xFFCA9FA8
	dc.l	0xFFCA9760
	dc.l	0xFFCA9788
	dc.l	L7961B0								;0x29 
	dc.l	0xFFCB0F28
	dc.l	0xFFCA9170
	dc.l	0xFFCACA70
	dc.l	0xFFCAC840
	dc.l	0xFFCACB30
	dc.l	0xFFCACB30
	dc.l	0xFFCAC7C0
	dc.l	0xFFCAC360
	dc.l	0xFFCAC460
	dc.l	0xFFCAC580 
	dc.l	0xFFCAC6C0
	dc.l	0xFFCABFB0
	dc.l	0xFFCAC160
	dc.l	0xFFCAC220
	dc.l	0xFFCAC2C0
	dc.l	0xFFCAC160
	dc.l	0xFFCABE60
	dc.l	0xFFCABDA0  
	dc.l	0xFFCABCD0
	dc.l	0xFFCABAC0 
	dc.l	0xFFCABBE0
	dc.l	0xFFCAAD50
	dc.l	0xFFCAADC0
	dc.l	0xFFCAAE30 
	dc.l	0xFFCAAE90 
	dc.l	0xFFCAAF70 
	dc.l	0xFFCAB000 
	dc.l	0xFFCAB0E0 
	dc.l	0xFFCAB1E0 
	dc.l	0xFFCAB250 
	dc.l	0xFFCAB350 
	dc.l	0xFFCAB3D0 
	dc.l	0xFFCAB4F0 
	dc.l	0xFFCAB570 
	dc.l	0xFFCAB660 
	dc.l	0xFFCAB6D0 
	dc.l	0xFFCAB740 
	dc.l	0xFFCAB7D0 
	dc.l	0xFFCAB850 
	dc.l	0xFFCAB8E0
	dc.l	0xFFCAB940 
	dc.l	0xFFCAB9D0
	dc.l	0xFFCABA50 
	dc.l	0xFFCAA910
	dc.l	0xFFCAAD20
	dc.l	0xFFCAAC10
	dc.l	0xFFCAAC80
	dc.l	0xFFCAACD0
	dc.l	0xFFCAAB10
	dc.l	0xFFCAAA60
	dc.l	0xFFCAA7B0
	dc.l	0xFFCAA620
	dc.l	0xFFCAA4D0
	dc.l	0xFFCAA370
	dc.l	0xFFCAA1D0
	dc.l	0xFFCAA160
	dc.l	0xFFCAA070
	dc.l	0xFFCAC910
	dc.l	0xFFCACB30
	dc.l	0xFFCACCB0
	dc.l	0xFFCAC9D0
	dc.l	0xFFCAABA0

L79522E:
	dc.b	"NIL",0x00
	dc.b	"BATTLETOADS",0x00
	dc.b	"Copyright 1992 Rare Ltd.",0x00
	dc.b	"PRESS BUTTON",0x00
	dc.b	"INSERT COIN",0x00
	dc.b	"INSERT",0x00
	dc.b	"PRESS",0x00
	dc.b	"CONTINUE",0x00
	dc.b	"GAME",0x00
	dc.b	"OVER",0x00
	dc.b	"PLEASE",0x00
	dc.b	"WAIT",0x00
	dc.b	"ANOTHER",0x00
	dc.b	"PRESS START",0x00
	dc.b	"0",0x00
L7952B2:
	dc.b	"SELECT",0x00
	dc.b	"PIMPLE",0x00
	dc.b	" RASH",0x00
	dc.b	" ZITZ",0x00
	dc.b	"A",0x00
	dc.b	"TOAD",0x00
	dc.b	"SELECTED",0x00
	dc.b	"ADDITIONAL COIN",0x00
	dc.b	"FREE",0x00
	dc.b	"PLAY",0x00
L7952F6:
	dc.b	"Use UP and DOWN to select item, and ACTION to choose",0x00
	dc.b	"    PRESS ANY TWO ACTION BUTTONS TOGETHER TO EXIT   ",0x00
	dc.b	"Move the joystick LEFT or RIGHT to select your character!",0x00
	dc.b	"Move the joystick LEFT or RIGHT to position",0x00
	dc.b	"the cursor, move UP or DOWN to change letters.",0x00
	dc.b	"Press any button to end!",0x00

L7959C4:
	dc.b	"HIT-FM  ",0x00
	dc.b	"        ",0x00
	dc.b	"SIZE    ",0x00
	dc.b	"OFFSET  ",0x00
	dc.b	"FRAME NO",0x00
	dc.b	"        ",0x00
	dc.b	"DEFN:   ",0x00
	dc.b	"ì"
	dc.b	"HOLDING ",0x00
	dc.b	"        ",0x00
	dc.b	"OBJHELD ",0x00
	dc.b	"INDEX NO",0x00
	dc.b	"        ",0x00
	dc.b	"DEFN:   ",0x00
	dc.b	"    ZERO",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"        ",0x00
	dc.b	"SLICE  /",0x00
	dc.b	"Y-SIZE  ",0x00
	dc.b	"HEIGHT  ",0x00
	dc.b	"HIT ID  ",0x00
	dc.b	"BLK Y = ",0x00
	dc.b	"BLK X = ",0x00
	dc.b	"HEIGHT  ",0x00
	dc.b	"SFX NO",0x00
	dc.b	"TUNE NO",0x00
	dc.b	"DLOAD NO",0x00
	dc.b	"Audio board running with    sound effects and    tunes.",0x00
	dc.b	"TB  TA  T9  T8  T7  T6  T5  T4  T3  T2  T1  T0",0x00
	dc.b	"F0  F1  F2  F3  F4  F5  F6  F7",0x00
	dc.b	"STEREO",0x00
	dc.b	"MONO",0x00
	dc.b	"CHAN PROC",0x00
	dc.b	"FREQ TRAN.",0x00
	dc.b	"Box number:",0x00
	dc.b	"Upload with:",0x00
	dc.b	"B         ,        ,<filename>",0x00
	dc.b	""HOLDFMS.BIN"",0x00
	dc.b	"SAVE",0x00

L79619A:
	dc.b	"@ & TM 1994 RARE LTD.",0x00
L7961B0:
	dc.b	"LICENSED TO ELECTRONIC ARTS BY RARE COIN GAMES, INC.",0x00

	dc.b	"@1994, Rare Coin Games, Inc.",0x00
